### ISSUE TITLE
Bad state: No element; scroll_controller.dart in ScrollController.get:position

### ISSUE THREAD

**Issue by The-Redhat** [peng8350/flutter_pulltorefresh#60]
The following error shows up on sentry:
```
StateError

Bad state: No element
scroll_controller.dart in ScrollController.get:position at line 112
scroll_controller.dart in ScrollController.get:offset at line 118
smart_refresher.dart in _SmartRefresherState._didChangeMode at line 210
smart_refresher.dart in _SmartRefresherState._init.<fn> at line 178
change_notifier.dart in ChangeNotifier.notifyListeners at line 206
change_notifier.dart in ValueNotifier.set:value at line 266
indicator_wrap.dart in Wrapper.set:mode at line 31
indicator_wrap.dart in RefreshWrapperState.onDragEnd at line 157
smart_refresher.dart in _SmartRefresherState._handleScrollEnd at line 114
smart_refresher.dart in _SmartRefresherState._dispatchScrollEvent at line 131
notification_listener.dart in NotificationListener._dispatch at line 127
notification_listener.dart in Notification.visitAncestor at line 45
scroll_notification.dart in _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor at line 31
framework.dart in Element.visitAncestorElements at line 3354
notification_listener.dart in Notification.dispatch at line 61
scroll_activity.dart in ScrollActivity.dispatchScrollUpdateNotification at line 96
scroll_position.dart in ScrollPosition.didUpdateScrollPositionBy at line 658
scroll_position.dart in ScrollPosition.setPixels at line 219
scroll_position_with_single_context.dart in ScrollPositionWithSingleContext.setPixels at line 84
scroll_activity.dart in BallisticScrollActivity.applyMoveTo at line 547
scroll_activity.dart in BallisticScrollActivity._tick at line 534
listener_helpers.dart in _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners at line 126
animation_controller.dart in AnimationController._tick at line 751
ticker.dart in Ticker._tick at line 228
binding.dart in _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback at line 990
binding.dart in _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<fn> at line 906
Called from: compact_hash.dart in __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach
binding.dart in _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame at line 904
binding.dart in _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame at line 834
```

**Comment by peng8350** [comment]
新版本mTry to see if this error still exists in the new version. Also, please describe how this happened. I don't understand just pasting logs.

**Comment by peng8350** [comment]
close,I think this issue has been fixed before

**Comment by furaiev** [comment]
Seems like this bug came back
```StateError
Bad state: No element
scroll_controller.dart in ScrollController.get:position at line 112
conversation_page.dart in _ConversationPageState._scrollToBottom.<fn> at line 302```
I haven't caught it myself yet, but it often comes from users to Sentry.
As soon as I reproduce it I'll et you know.
